# Generated by Django 4.2.30 on 2026-05-04 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('detections', '0001_initial'),
        ('sensors', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='detection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='detections.detection'),
        ),
        migrations.AddField(
            model_name='alert',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='alert',
            name='sensor_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='sensors.sensordata'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['farm', '-created_at'], name='alerts_farm_id_675685_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='alerts_severit_362484_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_resolved'], name='alerts_is_reso_d52617_idx'),
        ),
    ]
