# Generated by Django 4.2.30 on 2026-05-04 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detections/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('abnormal', 'Abnormal')], default='healthy', max_length=10)),
                ('confidence', models.FloatField(help_text='AI confidence score 0-1')),
                ('notes', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='devices.device')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='farms.farm')),
            ],
            options={
                'db_table': 'detections',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['farm', '-detected_at'], name='detections_farm_id_7525a8_idx'), models.Index(fields=['status'], name='detections_status_cb6d1a_idx')],
            },
        ),
    ]
