# Generated by Django 4.2.30 on 2026-05-04 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('camera', 'Camera'), ('sensor', 'Sensor')], max_length=10)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='farms.farm')),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm'], name='devices_farm_id_b4432f_idx'), models.Index(fields=['device_type'], name='devices_device__f7aa79_idx')],
            },
        ),
    ]
