# Generated by Django 4.2.30 on 2026-05-04 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Temperature in °C')),
                ('humidity', models.FloatField(help_text='Humidity in %')),
                ('gas_level', models.FloatField(help_text='Gas level in ppm')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='devices.device')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='farms.farm')),
            ],
            options={
                'db_table': 'sensor_data',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['farm', '-recorded_at'], name='sensor_data_farm_id_de3517_idx')],
            },
        ),
    ]
